api:
  build: .
  links:
    - 'db'
  volumes:
    - '.:/app'
    - '/app/node_modules'
  ports:
    - "0.0.0.0:9000:9000"
  env_file:
    - './local.env'

db:
  image: mvertes/alpine-mongo:3.2.1
  ports:
    - "27017"
  command: mongod
